title: A personal dump for ideas and beyond.
description: Mixture of reality and delusions
author: Hasan Denizkusu
github: https://github.com/hasanden
about: I'm an enthusiast of computer science, space and more stuff. 
disqus_shortname: unitingideas
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://x.com/seevogel93"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/hdenizkusu"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/hasanden"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://hasandenizkusu.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
